{% set name = "Redundans" %}
{% set version = "2.0.0" %}
{% set sha256hash = "02ec6b5991abf131e3abfae3c7e07975cd6138e0aba3efd0a3cb797b65ece940" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gabaldonlab/redundans/archive/v2.00.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  no_link:
   - bin/*.py

requirements:
  build:
    - make
    - zlib
    - tar
    - git
    - wget
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  host:
    - python >=3
    - pip
    - zlib
    - pillow
    - git
    - perl
    - make

  run:
    - python >=3
    - k8 >=0.2.5
    - perl
    - numpy
    - matplotlib-base
    - minimap2 >=2.24
    - miniasm >=0.3
    - gfastats >=1.3.6
    - meryl =1.3
    - bwa >=0.7.12
    - snap-aligner >=2.0.3
    - r-base >=4
    - r-argparse >=2.0.1
    - r-ggplot2 >=3.3.2
    - r-scales >=1.1.1

test:
  commands:
    - redundans.py --version

about:
  home: https://github.com/Gabaldonlab/redundans/
  license: GNU General Public License v3.0
  license_file: LICENSE
  summary: 'Redundans is a pipeline that assists an assembly of heterozygous/polymorphic genomes.'

extra:
  identifiers:
    - biotools:redundans
  recipe-maintainers:
    - Diego Fuentes Palacios
