{% set name = "Redundans" %}
{% set version = "2.0.1" %}
{% set sha256hash = "85a1937015aa0af44a5402761356c4098b085ee7233fb1b7cf8254e2ca0f0e54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gabaldonlab/redundans/archive/v2.01.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('redundans', max_pin="x") }}
  no_link:
   - bin/*.py

requirements:
  build:
    - make
    - zlib
    - tar
    - git
    - wget
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  host:
    - python >=3.8,<3.11
    - pip
    - zlib
    - pillow
    - git
    - perl
    - make

  run:
    - perl
    - numpy >=1.24.0
    - matplotlib-base >=3.7.3
    - python >=3.8,<3.11
    - minimap2 >=2.24
    - miniasm >=0.3
    - gfastats >=1.3.6
    - meryl =1.3
    - bwa >=0.7.12
    - snap-aligner >=2.0.3
    - r-base >=4
    - r-argparse >=2.0.1
    - r-ggplot2 >=3.3.2
    - r-scales >=1.1.1


about:
  home: https://github.com/Gabaldonlab/redundans/
  license: GNU General Public License v3.0
  license_file: LICENSE
  summary: 'Redundans is a pipeline that assists an assembly of heterozygous/polymorphic genomes.'

extra:
  identifiers:
    - biotools:redundans
  recipe-maintainers:
    - Diego Fuentes Palacios
